# Generated by Django 4.0.3 on 2022-04-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_quality_alter_bear_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='date',
            field=models.DateField(verbose_name='Quality Date'),
        ),
    ]
