# Generated by Django 4.0.3 on 2022-04-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_color_bear_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='date',
            field=models.DateField(verbose_name='Quality'),
        ),
    ]
